version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build-test-linux
      - build-test-linux-valgrind:
          requires:
            - build-test-linux
      - build-test-osx
      - build-test-windows

jobs:
  build-test-linux:
    docker:
      - image: ldcircleci/ld-c-sdk-ubuntu  # defined in sdks-ci-docker project
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: apt-get update -y && apt-get install -y git
      - run:
          name: Build
          command: mkdir -p build && cd build && cmake .. && make
      - run:
          name: Test
          command: cd build && GTEST_OUTPUT="xml:$(pwd)/.../reports/" make test

  build-test-linux-valgrind:
    docker:
      - image: ldcircleci/ld-c-sdk-ubuntu  # defined in sdks-ci-docker project
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: apt-get update -y && apt-get install -y git
      - run:
          name: Build
          command: mkdir -p build && cd build && cmake .. && make
      - run:
          name: Test with valgrind
          command: |
            cd build && make test
            valgrind --error-exitcode=100 --leak-check=full ./tests/google_tests

  build-test-osx:
    macos:
      xcode: "12.5.1"
    resource_class: macos.x86.medium.gen2
    environment:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      - run:
          name: Build
          command: mkdir -p build && cd build && cmake .. && make
      - run:
          name: Test
          command: cd build && GTEST_OUTPUT="xml:$(pwd)/.../reports/" make test

  build-test-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - checkout
      - run:
          name: build
          command: ./scripts/build.ps1
      - run:
          name: Test
          command: ./scripts/test.ps1
